### ISSUE TITLE
File structure - your JavaScript files are not "assets"

### ISSUE THREAD

**Issue by jsms90** [FAC10/week2-stopwatch-joey-piotr#20]
"Assets" usually describes things like image files.

If you have a `src` folder, the logic naming for the location of your frontend code is `public`

**Comment by joeylouise** [comment]
@jsms90 so should .js files go within the `public` folder?

**Comment by jsms90** [comment]
@joeylouise @PiotrBerebecki 

That was total nonsense.I'm very sorry guys. Ignore that advice. "Assets" absolutely does refer to things like CSS, JS, fonts, images
